from . import SQLModel, Field
from sqlmodel import Session, select, Relationship
from database import engine
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .pedido_producto import Pedido_producto

class Producto(SQLModel, table=True):
    id_producto: str = Field(max_length=50, primary_key=True)
    nombre: str = Field(max_length=500 , nullable=False)
    descripcion: str = Field(max_length=1000 , nullable=False)
    link_foto: str = Field(max_length=1000 , nullable=False)
    precio: int = Field(nullable=False)
    stock: int = Field(nullable=False)
    id_modelo: str = Field(max_length=50, foreign_key="modelo.id_modelo", nullable=False)
    id_marca: str = Field(max_length=50, foreign_key="marca.id_marca", nullable=False)

    pedido_productos: list["Pedido_producto"] = Relationship(back_populates="producto")

def crear_productos():
    productos = [
        Producto(id_producto="1", nombre="Camiseta gráfica de montaña", descripcion="Eleva tu guardarropa con esta elegante camiseta negra que presenta un impresionante gráfico de cordillera en blanco y negro. Perfecta para quienes aman la naturaleza o desean añadir un toque de diseño inspirado en ella a su look. Confeccionada en suave tela transpirable que garantiza comodidad todo el día. Ideal para salidas casuales o como regalo único, esta camiseta es una adición versátil a cualquier colección.", link_foto="https://i.imgur.com/QkIa5tT.jpeg", precio=500, stock=25, id_modelo="10", id_marca="1"),
        Producto(id_producto="2", nombre="Sudadera con capucha roja clásica", descripcion="Mejora tu vestuario casual con nuestra sudadera con capucha roja clásica. Confeccionada con una mezcla de algodón suave para máxima comodidad, esta vibrante sudadera roja cuenta con un bolsillo canguro, capucha con cordón ajustable y puños acanalados para un ajuste cómodo. Su diseño atemporal combina fácilmente con jeans o pantalones deportivos para un look relajado pero con estilo, convirtiéndola en una adición versátil a tu atuendo diario.", link_foto="https://i.imgur.com/1twoaDy.jpeg", precio=10, stock=0, id_modelo="10", id_marca="0"),
        Producto(id_producto="3", nombre="Sudadera gris Heather clásica", descripcion="Mantente cómodo y elegante con nuestra sudadera gris Heather clásica. Confeccionada en tela suave y duradera, incluye bolsillo canguro, capucha con cordón ajustable y puños acanalados. Perfecta para un día relajado fuera de casa o una tranquila velada en casa, esta sudadera es un complemento versátil para cualquier guardarropa.", link_foto="https://i.imgur.com/cHddUCu.jpeg", precio=69, stock=0, id_modelo="10", id_marca="1"),
        Producto(id_producto="4", nombre="Sudadera con capucha gris clásica", descripcion="Mejora tu vestuario casual con nuestra sudadera con capucha gris clásica. Elaborada con una suave mezcla de algodón, esta sudadera cuenta con un bolsillo canguro frontal, capucha con cordón ajustable y puños acanalados para un ajuste ceñido. Ideal para esas frescas tardes o los relajados fines de semana, combina a la perfección con tus jeans o pantalones deportivos favoritos.", link_foto="https://i.imgur.com/R2PN9Wq.jpeg", precio=90, stock=0, id_modelo="10", id_marca="0"),
        Producto(id_producto="5", nombre="Sudadera con capucha negra clásica", descripcion="Mejora tu vestuario casual con nuestra sudadera con capucha negra clásica. Fabricada con tejido suave y de alta calidad que garantiza comodidad y durabilidad, esta sudadera incluye un espacioso bolsillo canguro y una capucha con cordón ajustable. Su diseño versátil la hace perfecta para un relajado día en casa o una salida casual.", link_foto="https://i.imgur.com/cSytoSD.jpeg", precio=79, stock=0, id_modelo="10", id_marca="1"),
        Producto(id_producto="6", nombre="Pantalones deportivos clásicos de ajuste cómodo", descripcion="Descubre la combinación perfecta de estilo y comodidad con nuestros pantalones deportivos clásicos de ajuste cómodo. Estos versátiles pantalones negros cuentan con una cintura elástica suave con cordón ajustable, dos bolsillos laterales y puños acanalados en los tobillos para un ajuste seguro. Fabricados con un material ligero y duradero, son ideales tanto para días activos como para momentos de relajación.", link_foto="https://i.imgur.com/ZKGofuB.jpeg", precio=25, stock=0, id_modelo="10", id_marca="0"),
        Producto(id_producto="7", nombre="Pantalones deportivos clásicos con cordón", descripcion="Experimenta la combinación perfecta de comodidad y estilo con nuestros pantalones deportivos clásicos con cordón. Diseñados para un ajuste relajado, estos pantalones presentan una tela suave y elástica, prácticos bolsillos laterales y una cintura ajustable con cordón que incluye elegantes detalles en punta dorada. Ideales para descansar o hacer recados, estos pantalones se convertirán rápidamente en tu elección favorita para un uso casual sin esfuerzo.", link_foto="https://i.imgur.com/mp3rUty.jpeg", precio=79, stock=100, id_modelo="10", id_marca="1"),
        Producto(id_producto="8", nombre="Pantalones deportivos rojos clásicos", descripcion="Experimenta la máxima comodidad con nuestros pantalones deportivos rojos, perfectos tanto para sesiones de entrenamiento como para relajarte en casa. Confeccionados con una suave y duradera tela, estos pantalones incluyen una cintura ajustable con cordón, prácticos bolsillos laterales y un diseño entallado con puños elásticos que ofrecen un ajuste moderno y seguro. Su diseño contemporáneo te mantendrá con estilo mientras te mueves.", link_foto="https://i.imgur.com/9LFjwpI.jpeg", precio=98, stock=100, id_modelo="10", id_marca="0"),
        Producto(id_producto="9", nombre="Gorra de béisbol azul marino clásica", descripcion="Presume de estilo con esta elegante gorra de béisbol azul marino. Elaborada con material duradero, presenta un diseño estructurado y suave, junto con una correa ajustable para el ajuste perfecto. Protege tus ojos del sol y complementa tus looks casuales con este accesorio versátil y atemporal.", link_foto="https://i.imgur.com/R3iobJA.jpeg", precio=61, stock=100, id_modelo="10", id_marca="1"),
        Producto(id_producto="10", nombre="Gorra de béisbol azul clásica", descripcion="Corona tu look casual con nuestra gorra de béisbol azul clásica, fabricada con materiales de alta calidad para una comodidad duradera. Con su diseño de seis paneles y visera precurvada, esta gorra ofrece tanto estilo como funcionalidad para el uso diario.", link_foto="https://i.imgur.com/wXuQ7bm.jpeg", precio=86, stock=100, id_modelo="10", id_marca="0"),
        Producto(id_producto="11", nombre="Gorra de béisbol roja clásica", descripcion="Mejora tu vestuario casual con esta atemporal gorra de béisbol roja. Fabricada con material resistente, ofrece un ajuste cómodo gracias a su correa ajustable trasera. Ideal para los días soleados o para añadir un toque deportivo a tu outfit.", link_foto="https://i.imgur.com/cBuLvBi.jpeg", precio=35, stock=100, id_modelo="11", id_marca="1"),
        Producto(id_producto="12", nombre="Gorra de béisbol negra clásica", descripcion="Mejora tu vestuario casual con esta elegante gorra de béisbol negra. Confeccionada con tejido transpirable de alta calidad, incluye una correa ajustable para un ajuste perfecto. Tanto si sales a correr como si simplemente haces recados, esta gorra añadirá un toque de estilo a cualquier conjunto.", link_foto="https://i.imgur.com/KeqG6r4.jpeg", precio=58, stock=100, id_modelo="11", id_marca="0"),
        Producto(id_producto="13", nombre="Shorts clásicos de chino verde oliva", descripcion="Mejora tu guardarropa casual con estos clásicos shorts de chino verde oliva. Diseñados para ofrecer comodidad y versatilidad, cuentan con una cintura suave, prácticos bolsillos y un corte entallado que los hace perfectos tanto para fines de semana relajados como para ocasiones semiinformales. El tejido resistente asegura que mantengan su forma durante tus actividades diarias mientras conservan su aspecto elegante.", link_foto="https://i.imgur.com/UsFIvYs.jpeg", precio=84, stock=100, id_modelo="11", id_marca="1"),
        Producto(id_producto="14", nombre="Shorts deportivos clásicos de talle alto", descripcion="Mantente cómodo y con estilo con nuestros shorts deportivos clásicos de talle alto. Diseñados para ofrecer máximo movimiento y versatilidad, estos shorts son imprescindibles en tu vestuario de entrenamiento. Con un talle favorecedor, tejido transpirable y ajuste seguro que se mantiene en su lugar durante cualquier actividad, son perfectos para el gimnasio, correr o incluso para uso casual.", link_foto="https://i.imgur.com/eGOUveI.jpeg", precio=43, stock=100, id_modelo="11", id_marca="0"),
        Producto(id_producto="15", nombre="Camiseta blanca clásica de cuello redondo", descripcion="Mejora tus básicos con esta versátil camiseta blanca de cuello redondo. Confeccionada en una suave mezcla de algodón, ofrece comodidad y durabilidad. Su diseño sencillo y atemporal combina fácilmente con prácticamente cualquier conjunto. Ideal para capas o para usarla sola, esta camiseta es un básico imprescindible en cualquier guardarropa.", link_foto="https://i.imgur.com/axsyGpD.jpeg", precio=39, stock=100, id_modelo="11", id_marca="1"),
        Producto(id_producto="16", nombre="Camiseta blanca clásica - Estilo y comodidad atemporal", descripcion="Mejora tu vestuario diario con nuestra camiseta blanca clásica. Elaborada con suave algodón premium, esta versátil camiseta combina comodidad con durabilidad, perfecta para el uso cotidiano. Con un corte relajado unisex que favorece a todo tipo de cuerpos, es una prenda básica para cualquier conjunto casual. Fácil de cuidar y lavable a máquina, esta camiseta blanca mantiene su forma y suavidad lavado tras lavado. Combínala con tus jeans favoritos o úsala bajo una chaqueta para un look más refinado.", link_foto="https://i.imgur.com/Y54Bt8J.jpeg", precio=73, stock=100, id_modelo="11", id_marca="0"),
        Producto(id_producto="17", nombre="Camiseta negra clásica", descripcion="Mejora tu estilo diario con nuestra camiseta negra clásica. Esta prenda básica está confeccionada en suave algodón transpirable para una comodidad que dura todo el día. Su versátil diseño presenta un cuello redondo y mangas cortas, lo que la hace perfecta para usar sola o en capas. Duradera y fácil de cuidar, seguramente se convertirá en un favorito de tu guardarropa.", link_foto="https://i.imgur.com/9DqEOV5.jpeg", precio=35, stock=100, id_modelo="11", id_marca="1"),
        Producto(id_producto="18", nombre="Controlador de juego inalámbrico blanco y naranja", descripcion="Mejora tu experiencia de juego con este controlador inalámbrico de última generación, con base blanca y vibrantes acentos naranjas. Diseñado para precisión, su forma ergonómica y botones sensibles garantizan el máximo control y comodidad durante horas de juego. Compatible con múltiples plataformas, este controlador es imprescindible para cualquier jugador serio que busque mejorar su configuración.", link_foto="https://i.imgur.com/ZANVnHE.jpeg", precio=69, stock=100, id_modelo="20", id_marca="0"),
        Producto(id_producto="19", nombre="Set de auriculares inalámbricos y audífonos", descripcion="Experimenta la fusión de estilo y sonido con este sofisticado set de audio que incluye auriculares inalámbricos blancos con sonido cristalino y audífonos duraderos perfectos para un estilo de vida activo. Diseñado para amantes de la música que valoran tanto la apariencia como la fidelidad del audio, este versátil dúo satisface todas tus necesidades auditivas.", link_foto="https://i.imgur.com/yVeIeDa.jpeg", precio=44, stock=100, id_modelo="20", id_marca="1"),
        Producto(id_producto="20", nombre="Auriculares over-ear cómodos y elegantes", descripcion="Experimenta una calidad de sonido superior con nuestros auriculares over-ear cómodos y elegantes, diseñados para uso prolongado con copas acolchadas y diadema ajustable y acolchada. Ideales para una escucha inmersiva, ya sea en casa, en la oficina o en movimiento. Su construcción duradera y diseño atemporal ofrecen tanto un aspecto estético como un rendimiento duradero.", link_foto="https://i.imgur.com/SolkFEB.jpeg", precio=28, stock=100, id_modelo="20", id_marca="0"),
        Producto(id_producto="21", nombre="Tostadora eficiente de 2 ranuras", descripcion="Mejora tu rutina matutina con nuestra elegante tostadora de 2 ranuras, que incluye controles de tostado ajustables y una bandeja extraíble para migas para una fácil limpieza. Este práctico y elegante electrodoméstico es perfecto para cualquier cocina, asegurando que tu pan tostado siempre quede dorado y delicioso.", link_foto="https://i.imgur.com/keVCVIa.jpeg", precio=48, stock=100, id_modelo="20", id_marca="1"),
        Producto(id_producto="22", nombre="Ratón inalámbrico para computadora", descripcion="Experimenta una navegación suave y precisa con este ratón inalámbrico moderno, que presenta un acabado brillante y un diseño ergonómico cómodo. Su seguimiento sensible y su interfaz fácil de usar lo convierten en el accesorio perfecto para cualquier configuración de escritorio o portátil. El vibrante tono azul añade un toque de color a tu espacio de trabajo, mientras que su tamaño compacto asegura que quepa perfectamente en tu bolso para la productividad sobre la marcha.", link_foto="https://i.imgur.com/w3Y8NwQ.jpeg", precio=10, stock=100, id_modelo="20", id_marca="0"),
        Producto(id_producto="23", nombre="Portátil moderno con iluminación ambiental", descripcion="Experimenta la informática del siguiente nivel con nuestro portátil ultradelgado, que presenta una impresionante pantalla con iluminación ambiental. Esta máquina de alto rendimiento es perfecta tanto para trabajar como para jugar, ofreciendo un potente procesamiento en un diseño elegante y portátil. Los colores vibrantes añaden un toque de personalidad a tu colección tecnológica, haciéndolo tan estiloso como funcional.", link_foto="https://i.imgur.com/OKn1KFI.jpeg", precio=43, stock=100, id_modelo="21", id_marca="1"),
        Producto(id_producto="24", nombre="Portátil moderno para profesionales", descripcion="Experimenta tecnología de vanguardia y diseño elegante con nuestro último modelo de portátil. Perfecto para profesionales en movimiento, este portátil de alto rendimiento cuenta con un potente procesador, amplio almacenamiento y una batería de larga duración, todo en un marco ligero y delgado para máxima portabilidad. Compra ahora para elevar tu trabajo y juego.", link_foto="https://i.imgur.com/ItHcq7o.jpeg", precio=97, stock=100, id_modelo="21", id_marca="0"),
        Producto(id_producto="25", nombre="Auriculares over-ear rojos y plateados", descripcion="Sumérgete en una calidad de sonido superior con estos elegantes auriculares over-ear rojos y plateados. Diseñados para comodidad y estilo, cuentan con copas acolchadas, diadema ajustable y acolchada, y un cable rojo desmontable para fácil almacenamiento y portabilidad. Perfectos para amantes de la música y audiófilos que valoran tanto la apariencia como la fidelidad del audio.", link_foto="https://i.imgur.com/YaSqa06.jpeg", precio=39, stock=100, id_modelo="21", id_marca="1"),
        Producto(id_producto="26", nombre="Funda de teléfono con acabado espejo", descripcion="Mejora la apariencia de tu smartphone con esta funda ultra elegante con acabado espejo. Diseñada para ofrecer estilo con protección, la funda presenta una superficie reflectante que añade un toque de elegancia mientras mantiene tu dispositivo seguro de arañazos e impactos. Perfecta para quienes aman una estética minimalista y moderna.", link_foto="https://i.imgur.com/yb9UQKL.jpeg", precio=27, stock=100, id_modelo="21", id_marca="0"),
        Producto(id_producto="27", nombre="Reloj inteligente con pantalla vibrante", descripcion="Experimenta la medición del tiempo moderna con nuestro reloj inteligente de alta tecnología, que incluye una vívida pantalla táctil, esferas de reloj personalizables y una cómoda correa de silicona azul. Este reloj te mantiene conectado con notificaciones y seguimiento de actividad física mientras muestra un estilo y versatilidad excepcionales.", link_foto="https://i.imgur.com/LGk9Jn2.jpeg", precio=16, stock=100, id_modelo="21", id_marca="1"),
        Producto(id_producto="28", nombre="Sofá de cuero moderno y elegante", descripcion="Mejora la elegancia de tu sala de estar con nuestro sofá de cuero moderno y elegante. Diseñado con una estética minimalista, presenta líneas limpias y un acabado de cuero lujoso. Las robustas patas metálicas proporcionan estabilidad y soporte, mientras que los cojines mullidos garantizan comodidad. Perfecto para hogares contemporáneos o áreas de espera de oficinas, este sofá es una pieza de declaración que combina estilo con practicidad.", link_foto="https://i.imgur.com/Qphac99.jpeg", precio=53, stock=10, id_modelo="30", id_marca="0"),
        Producto(id_producto="29", nombre="Mesa de comedor de madera estilo mid-century", descripcion="Eleva tu comedor con esta mesa de comedor estilo mid-century moderna, que presenta un elegante acabado en nogal y patas cónicas para una estética atemporal. Su robusta construcción de madera y diseño minimalista la convierten en una pieza versátil que combina con diversos estilos de decoración. Perfecta para cenas íntimas o como un elegante lugar para tu café matutino.", link_foto="https://i.imgur.com/DMQHGA0.jpeg", precio=24, stock=10, id_modelo="30", id_marca="1"),
        Producto(id_producto="30", nombre="Mesa de comedor con base dorada y tapa de piedra", descripcion="Mejora tu espacio de comedor con esta lujosa mesa, que presenta una resistente base de metal dorado con un intrincado diseño de varillas que proporciona estabilidad y elegancia. La lisa tapa de piedra en forma redonda ofrece una superficie robusta para tus momentos de comida. Perfecta tanto para comidas diarias como para ocasiones especiales, esta mesa complementa fácilmente cualquier decoración moderna o glamorosa.", link_foto="https://i.imgur.com/NWIJKUj.jpeg", precio=66, stock=10, id_modelo="30", id_marca="0"),
        Producto(id_producto="31", nombre="Sillón moderno de elegancia en verde azulado", descripcion="Mejora tu espacio vital con este hermosamente elaborado sillón, que presenta un marco de madera elegante que complementa su tapizado verde azulado vibrante. Ideal para añadir un toque de color y estilo contemporáneo a cualquier habitación, esta silla ofrece una excelente comodidad y sofisticación. Perfecta para leer, relajarse o crear un acogedor rincón de conversación.", link_foto="https://i.imgur.com/6wkyyIN.jpeg", precio=25, stock=10, id_modelo="30", id_marca="1"),
        Producto(id_producto="32", nombre="Mesa de comedor de madera maciza elegante", descripcion="Mejora tu espacio de comedor con esta mesa de comedor contemporánea y elegante, elaborada en madera maciza de alta calidad con un acabado cálido. Su robusta construcción y diseño minimalista la convierten en una adición perfecta para cualquier hogar que busque un toque de elegancia. Acomoda cómodamente hasta seis comensales e incluye un llamativo centro de mesa con frutas. La iluminación superior no está incluida.", link_foto="https://i.imgur.com/4lTaHfF.jpeg", precio=67, stock=10, id_modelo="30", id_marca="0"),
        Producto(id_producto="33", nombre="Estación de trabajo minimalista moderna", descripcion="Eleva tu oficina en casa con nuestra estación de trabajo minimalista moderna, que incluye un elegante escritorio de madera con una computadora sofisticada, una lámpara de escritorio ajustable de madera y accesorios complementarios para un espacio de trabajo limpio y productivo. Este conjunto es perfecto para profesionales que buscan un look contemporáneo que combine funcionalidad con diseño.", link_foto="https://i.imgur.com/3oXNBst.jpeg", precio=49, stock=10, id_modelo="31", id_marca="1"),
        Producto(id_producto="34", nombre="Silla de oficina ergonómica moderna", descripcion="Mejora tu espacio de oficina con esta elegante y cómoda silla de oficina ergonómica moderna. Diseñada para proporcionar soporte óptimo durante la jornada laboral, incluye un mecanismo de altura ajustable, ruedas suaves para fácil movilidad y un asiento acolchado para mayor comodidad durante largos periodos. Sus líneas limpias y diseño blanco minimalista la convierten en una adición versátil a cualquier espacio de trabajo contemporáneo.", link_foto="https://i.imgur.com/3dU0m72.jpeg", precio=71, stock=10, id_modelo="31", id_marca="0"),
        Producto(id_producto="35", nombre="Botines de fútbol holográficos futuristas", descripcion="Pisa el campo y destaca entre la multitud con estos llamativos botines de fútbol holográficos. Diseñados para el jugador moderno, estos botines presentan una silueta elegante, construcción ligera para máxima agilidad y tacos duraderos para una tracción óptima. El acabado holográfico brillante refleja un arcoíris de colores mientras te mueves, asegurando que te noten tanto por tus habilidades como por tu estilo. Perfecto para el atleta a la moda que quiere hacer una declaración.", link_foto="https://i.imgur.com/qNOjJje.jpeg", precio=39, stock=10, id_modelo="40", id_marca="1"),
        Producto(id_producto="36", nombre="Tacones altos con brillo arcoíris", descripcion="Entra en el centro de atención con estos llamativos tacones altos con brillo arcoíris. Diseñados para deslumbrar, cada zapato muestra un caleidoscopio de colores brillantes que captan y reflejan la luz con cada paso. Perfectos para ocasiones especiales o una noche de fiesta, estos zapatos seguramente llamarán la atención y elevarán cualquier conjunto.", link_foto="https://i.imgur.com/62gGzeF.jpeg", precio=39, stock=10, id_modelo="40", id_marca="0"),
        Producto(id_producto="37", nombre="Sandalias de esparto denim chic para verano", descripcion="Pisa el verano con estilo con nuestras sandalias de esparto denim chic. Con suela de yute trenzado para un toque clásico y correas denim ajustables para un ajuste ceñido, estas sandalias ofrecen comodidad y un borde a la moda. El diseño fácil de poner asegura conveniencia para días de playa o salidas casuales.", link_foto="https://i.imgur.com/9qrmE1b.jpeg", precio=33, stock=10, id_modelo="40", id_marca="1"),
        Producto(id_producto="38", nombre="Zapatillas vibrantes: zapatillas deportivas naranja y azul", descripcion="Pisa con estilo con estas llamativas zapatillas deportivas que presentan una combinación impactante de tonos naranja y azul. Diseñadas tanto para comodidad como moda, estos zapatos vienen con suelas flexibles y plantillas acolchadas, ideales para personas activas que no comprometen el estilo. Los detalles reflectantes plateados añaden un toque de modernidad, convirtiéndolas en un accesorio destacado para tu entrenamiento o vestuario casual.", link_foto="https://i.imgur.com/hKcMNJs.jpeg", precio=27, stock=10, id_modelo="40", id_marca="0"),
        Producto(id_producto="39", nombre="Zapatillas clásicas rosas vibrantes", descripcion="Pisa con estilo con nuestras Zapatillas Clásicas Rosas Vibrantes! Estos llamativos zapatos presentan un audaz tono rosa con detalles blancos icónicos, ofreciendo un diseño elegante y atemporal. Construidos con materiales duraderos y un ajuste cómodo, son perfectos para quienes buscan añadir un toque de color a su calzado diario. ¡Consigue un par hoy y añade algo de vibrancia a tu paso!", link_foto="https://i.imgur.com/mcW42Gi.jpeg", precio=84, stock=10, id_modelo="40", id_marca="1"),
        Producto(id_producto="40", nombre="Zapatilla futurista plateada y dorada de caña alta", descripcion="Adéntrate en el futuro con esta llamativa zapatilla de caña alta, diseñada para quienes se atreven a destacar. La zapatilla presenta un cuerpo plateado con llamativos acentos dorados, ofreciendo un giro moderno al calzado clásico. Su diseño de caña alta proporciona soporte y estilo, convirtiéndola en la adición perfecta a cualquier colección de moda vanguardista. ¡Consigue un par hoy y eleva tu juego de zapatos!", link_foto="https://i.imgur.com/npLfCGq.jpeg", precio=68, stock=10, id_modelo="41", id_marca="0"),
        Producto(id_producto="41", nombre="Botines futuristas chic de tacón alto", descripcion="Eleva tu estilo con nuestros botines de tacón alto vanguardistas que combinan diseño atrevido con estética avant-garde. Estos botines presentan un tacón de bloques de color único, una silueta elegante y un acabado en gris claro versátil que combina fácilmente con cualquier atuendo moderno. Diseñados para el individuo a la moda, estos botines seguramente harán una declaración.", link_foto="https://i.imgur.com/HqYqLnW.jpeg", precio=36, stock=10, id_modelo="41", id_marca="1"),
        Producto(id_producto="42", nombre="Zapatos de tacón peep-toe de cuero charol con tacón dorado", descripcion="Pisa con sofisticación con estos elegantes zapatos peep-toe, que muestran un acabado brillante de cuero charol y un llamativo tacón de bloque en tono dorado. El detalle ornamental del broche añade un toque de glamour, perfecto para elevar tu atuendo de noche o complementar un look pulido durante el día.", link_foto="https://i.imgur.com/AzAY4Ed.jpeg", precio=53, stock=10, id_modelo="41", id_marca="0"),
        Producto(id_producto="43", nombre="Mocasines elegantes de cuero morado", descripcion="Pisa con sofisticación con nuestros Mocasines Elegantes de Cuero Morado, perfectos para hacer una declaración audaz. Elaborados en cuero de alta calidad con un acabado morado vibrante, estos zapatos presentan una silueta clásica de mocasín actualizada con un toque contemporáneo. El diseño cómodo de ponerse fácilmente y las suelas duraderas aseguran tanto estilo como funcionalidad para el hombre moderno.", link_foto="https://i.imgur.com/Au8J9sX.jpeg", precio=17, stock=10, id_modelo="41", id_marca="1"),
        Producto(id_producto="44", nombre="Zapatos casuales clásicos de gamuza azul", descripcion="Pisa con comodidad con nuestros Zapatos Casuales Clásicos de Gamuza Azul, perfectos para el uso diario. Estos zapatos presentan una parte superior de gamuza azul elegante, suelas de goma duraderas para una tracción superior y frentes con cordones clásicos para un ajuste ceñido. El diseño elegante combina bien tanto con jeans como con chinos, convirtiéndolos en una adición versátil a cualquier guardarropa.", link_foto="https://i.imgur.com/sC0ztOB.jpeg", precio=39, stock=10, id_modelo="41", id_marca="0"),
        Producto(id_producto="45", nombre="Bicicleta eléctrica futurista elegante", descripcion="Esta moderna bicicleta eléctrica combina estilo y eficiencia con su diseño único y características de rendimiento de primera categoría. Equipada con un marco duradero, batería de larga duración y capacidades tecnológicas integradas, es perfecta para el viajero ecológico que busca moverse por la ciudad con facilidad.", link_foto="https://i.imgur.com/BG8J0Fj.jpg", precio=22, stock=20, id_modelo="50", id_marca="1"),
        Producto(id_producto="46", nombre="Kart todoterreno elegante", descripcion="Experimenta la emoción de las aventuras al aire libre con nuestro Kart Todoterreno Elegante, que incluye un marco duradero, asiento de carreras cómodo y robustos neumáticos con dibujo grande perfectos para manejar diversos terrenos. Diseñado para buscadores de diversión de todas las edades, este kart es una elección ideal para carreras en el patio o explorar senderos locales.", link_foto="https://i.imgur.com/Ex5x3IU.jpg", precio=37, stock=20, id_modelo="50", id_marca="0"),
        Producto(id_producto="47", nombre="Eau de Parfum cítrico radiante", descripcion="Date el gusto con la esencia del verano con este vibrante Eau de Parfum con aroma cítrico. Presentado en un elegante frasco de vidrio con un tapón naranja audaz, esta fragancia encarna frescura y elegancia. Perfecta para el uso diario, es una delicia olfativa que deja una impresión duradera y vigorizante.", link_foto="https://i.imgur.com/xPDwUb3.jpg", precio=73, stock=20, id_modelo="50", id_marca="1"),
        Producto(id_producto="48", nombre="Equipaje de cabina elegante verde oliva", descripcion="Viaja con estilo con nuestro equipaje de cabina resistente, perfecto para escapadas de fin de semana o viajes de negocios. Esta elegante maleta verde oliva cuenta con ruedas que giran suavemente para navegar fácilmente por el aeropuerto, un mango telescópico resistente y un compartimento con cremallera para mantener tus pertenencias seguras. Su tamaño compacto cumple con los requisitos de la mayoría de los compartimentos superiores de las aerolíneas, garantizando una experiencia de vuelo sin problemas.", link_foto="https://i.imgur.com/jVfoZnP.jpg", precio=48, stock=20, id_modelo="50", id_marca="0"),
        Producto(id_producto="49", nombre="Bolso de moda transparente chic", descripcion="Eleva tu estilo con nuestro Bolso de Moda Transparente Chic, perfecto para mostrar tus esenciales con un borde moderno y claro. Este accesorio de moda presenta una construcción de acrílico duradero, herrajes dorados elegantes y una correa de cadena. Su tamaño compacto asegura que puedas llevar tus artículos diarios con facilidad y sofisticación.", link_foto="https://i.imgur.com/Lqaqz59.jpg", precio=61, stock=20, id_modelo="51", id_marca="1"),
        Producto(id_producto="50", nombre="Juego de vasos de vidrio elegantes", descripcion="Mejora tu colección de vajilla con nuestro sofisticado juego de vasos de vidrio, perfecto para servir tus bebidas favoritas. Este versátil set incluye tanto vasos transparentes como ligeramente tintados, añadiendo un toque moderno a cualquier mesa. Elaborados con materiales de calidad, estos vasos duraderos están diseñados para resistir el uso diario mientras mantienen su atractivo elegante.", link_foto="https://i.imgur.com/TF0pXdL.jpg", precio=50, stock=20, id_modelo="51", id_marca="0")
    ]

    with Session(engine) as sesion:
        productos_existentes = sesion.exec(select(Producto)).all()
        if not productos_existentes:
            sesion.add_all(productos)
            sesion.commit()
            print("Productos creados")
        else:
            print("Productos ya existen")